### ISSUE TITLE
Add disable of FSM functionality for "17_3441_MaxRoCoF" case 

### ISSUE THREAD

**Issue by Jacob-Bak-Mortensen** [Energinet-AIG/PP-MTB#105]
Hey,

I ran the PP-MTB in PowerFactory and noticed that the active power reacted to the frequency change in the "17_3441_MaxRoCoF" case. I would say that FSM should be disabled during the case.
Of course, if this is on purpose that the FSM is left enabled then there is no issue. :)

**After the PP-MTB finished:**
![MaxRoCof with FSM enabled](https://user-images.githubusercontent.com/122613977/225827402-96a49578-f98c-4fb4-9525-dd2efcffb5f7.png)
**After disable of FSM:**
![MaxRoCof with FSM disabled](https://user-images.githubusercontent.com/122613977/225827408-d34f2796-477d-4fae-ace3-6b3a0669bbfd.png)

**Comment by matbkri** [comment]
Hello Jacob. We agree. Thanks for the feedback. We already have a similar issue #3. I have included a note about this in that issue.
