### ISSUE TITLE
Minor bug in script "PP-MTB Execute_Energinet_V1.8"

### ISSUE THREAD

**Issue by bakhtyar0** [Energinet-AIG/PP-MTB#112]
In the following part of code:
If y<10 then the out files will only have one index, therefore i+"_01" and +"_02" should be removed.

for x in range(TotalSmltRun):
    y = x+1;
    if y < 10:
        File.convert_out_to_csv(src_folder, projectname+"_0"+str(y)+"_01"+".out", projectname+"_0"+str(y)+"_01"+".csv")
        File.convert_out_to_csv(src_folder, projectname+"_0"+str(y)+"_02"+".out", projectname+"_0"+str(y)+"_02"+".csv")
    else:
        File.convert_out_to_csv(src_folder, projectname+"_"+str(y)+"_01"+".out", projectname+"_"+str(y)+"_01"+".csv")
        File.convert_out_to_csv(src_folder, projectname+"_"+str(y)+"_02"+".out", projectname+"_"+str(y)+"_02"+".csv")

**Comment by matbkri** [comment]
Hello Bakhtyar. Thanks for reporting a bug. We really value any and all feedback. That is an outdated version of the PSCAD script. Please download and use the latests version from the release page: https://github.com/Energinet-AIG/PP-MTB/releases.

Best regards Mathias
