### ISSUE TITLE
Removal of PP-MTB warnings in PSCAD model

### ISSUE THREAD

**Issue by Jacob-Bak-Mortensen** [Energinet-AIG/PP-MTB#123]
Hey,
A small thing, could you add correct typing for removal of below warnings in PSCAD.
Not a big deal, but it is also easily fixed.

![image](https://github.com/Energinet-AIG/PP-MTB/assets/122613977/448a5f6d-bba5-4b4e-99df-4b455c394fce)
![image](https://github.com/Energinet-AIG/PP-MTB/assets/122613977/cb3e2bb3-63c7-419d-8677-fa6a6e41402f)

**Comment by matbkri** [comment]
Closed by #125
