### ISSUE TITLE
Move all documentation to GitHub wiki

### ISSUE THREAD

**Issue by matbkri** [Energinet-AIG/PP-MTB#5]
Move all tool guides and other documentation to the GitHub wiki.

**Comment by CVLenerginet** [comment]
All outside documentation is moved to GitHub wiki. Further wiki updates will me made in #12, #14, #15 and #24.

* [quickstart_pf](https://github.com/Energinet-AIG/PP-MTB/blob/main/Powerfactory/quickstart_pf.pdf) -> [Quickstart Guide PowerFactory](https://github.com/Energinet-AIG/PP-MTB/wiki/Quickstart-Guide-PowerFactory)
* [Manual_PP-MTB_PSCAD_V1.8](https://github.com/Energinet-AIG/PP-MTB/blob/main/PSCAD/DK1_DSO_D/Manual_PP-MTB_PSCAD_V1.8.pptx) -> [Quickstart Guide PSCAD](https://github.com/Energinet-AIG/PP-MTB/wiki/Quickstart-Guide-PSCAD)
* [quickstart_plotter](https://github.com/Energinet-AIG/PP-MTB/blob/main/Plotter/quickstart_plotter.pdf) -> [Quickstart Guide Plotter](https://github.com/Energinet-AIG/PP-MTB/wiki/Quickstart-Guide-Plotter)
* Excel quickstart guide -> [Quickstart Guide Excel](https://github.com/Energinet-AIG/PP-MTB/wiki/Quickstart-Guide-Excel)

**Comment by CVLenerginet** [comment]
All outside documentation is moved to GitHub wiki. Further wiki updates will me made in #12, #14, #15 and #24.

* [quickstart_pf](https://github.com/Energinet-AIG/PP-MTB/blob/main/Powerfactory/quickstart_pf.pdf) -> [Quickstart Guide PowerFactory](https://github.com/Energinet-AIG/PP-MTB/wiki/Quickstart-Guide-PowerFactory)
* [Manual_PP-MTB_PSCAD_V1.8](https://github.com/Energinet-AIG/PP-MTB/blob/main/PSCAD/DK1_DSO_D/Manual_PP-MTB_PSCAD_V1.8.pptx) -> [Quickstart Guide PSCAD](https://github.com/Energinet-AIG/PP-MTB/wiki/Quickstart-Guide-PSCAD)
* [quickstart_plotter](https://github.com/Energinet-AIG/PP-MTB/blob/main/Plotter/quickstart_plotter.pdf) -> [Quickstart Guide Plotter](https://github.com/Energinet-AIG/PP-MTB/wiki/Quickstart-Guide-Plotter)
* Excel quickstart guide -> [Quickstart Guide Excel](https://github.com/Energinet-AIG/PP-MTB/wiki/Quickstart-Guide-Excel)
